# Generated by Django 5.2.3 on 2025-07-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_title_todo_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='nombre',
            new_name='title',
        ),
    ]
